spring:
  application:
    name: auth-server

  mail:
    host: ${MAILTRAP_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAILTRAP_PORT:2525}
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    from: ${MAILTRAP_FROM}
    frontend:
      url: ${FRONTEND_URL}
    
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST:http://localhost:7777}"

  datasource:
    url: jdbc:h2:mem:users;

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  mvc:
    problemdetails:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}


server:
  port: 3000

  servlet:
    context-path: /auth-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

auth:
  jwt: 
    access-token-expiration: 900
  refresh-token:
    expiration: 604800