spring:
  application:
    name: notification-ms
  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST:http://localhost:7777}"

  datasource:
    username: ${db.username:root}
    password: ${db.password:123456}
    url: ${db.url:jdbc:mysql://db-notification:3306/notification_db}
    hikari:
      connection-timeout: ${db.connection-timeout:30000}
      maximum-pool-size: ${db.maximum-pool-size:10}
  cloud:
    function:
      definition: appointmentCreatedConsumer;appointmentConfirmedConsumer;appointmentCompletedConsumer;appointmentCanceledConsumer;patientCreatedConsumer

    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKER:kafka-hospital:29092}

      bindings:

        appointmentCreatedConsumer-in-0:
          destination: appointment-created
          group: notification-group
          content-type: application/json

        appointmentUpdatedStatusConsumer-in-0:
          destination: appointment-updated-status
          group: notification-group
          content-type: application/json

        patientCreatedConsumer-in-0:
          destination: patient-created
          group: notification-group
          content-type: application/json

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://ms-registry-server:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
server:
  port: 8081

  servlet:
    context-path: /notifications

scalar:
  enabled: false
  darkMode: true
  theme: deepSpace