spring:
  application:
    name: gateway
  profiles:
    default: oauth2   # o eureka-on-cb, eureka-on, eureka-off

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER_JWKS_URI:http://localhost:3000/auth-server/.well-known/jwks.json}
server:
  port: 4040

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://ms-registry-server:8761/eureka}
    fetch-registry: true
  
