spring:
  application:
    name: appointment-ms

  profiles:
    default: prod

  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST:http://localhost:7777}"

  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKER:kafka-hospital:29092}

      bindings:
        appointment-created-out-0:
          destination: appointment-created
          content-type: application/json

        appointment-confirmed-out-0:
          destination: appointment-confirmed
          content-type: application/json
        appointment-completed-out-0:
          destination: appointment-completed
          content-type: application/json

        appointment-canceled-out-0:
          destination: appointment-canceled
          content-type: application/json
    openfeign:
      circuitbreaker:
        enabled: true


  datasource:
    username: ${db.username:postgres}
    password: ${db.password:123456}
    url: ${db.url:jdbc:postgresql://localhost:5434/hospital_db}
    hikari:
      connection-timeout: ${db.connection-timeout:30000}
      maximum-pool-size: ${db.maximum-pool-size:10}

resilience4j:
  circuitbreaker:
    instances:
      patient-ms:
        # Configuración del sliding window para tipo COUNT_BASED
        slidingWindowType: COUNT_BASED
        # Tamaño del sliding window que es la cantidad de calls que se consideran para evaluar el circuit breaker
        slidingWindowSize: 5
        # Mínimo número de calls para evaluar el circuit breaker
        minimumNumberOfCalls: 5
        # Threshold de fallos para abrir el circuito
        failureRateThreshold: 50
        # Duración en estado abierto antes de pasar a half-open
        waitDurationInOpenState: 10s
        # Número de calls permitidos en estado half-open
        permittedNumberOfCallsInHalfOpenState: 2
        ignoreExceptions:
          - personal.appointment_ms.exceptions.PatientNotFoundException
          - feign.FeignException.BadRequest      # 400
          - feign.FeignException.UnprocessableEntity  # 422
      doctor-ms:
        # Configuración del sliding window para tipo COUNT_BASED
        slidingWindowType: COUNT_BASED
        # Tamaño del sliding window que es la cantidad de calls que se consideran para evaluar el circuit breaker
        slidingWindowSize: 5
        # Mínimo número de calls para evaluar el circuit breaker
        minimumNumberOfCalls: 5
        # Threshold de fallos para abrir el circuito
        failureRateThreshold: 50
        # Duración en estado abierto antes de pasar a half-open
        waitDurationInOpenState: 10s
        # Número de calls permitidos en estado half-open
        permittedNumberOfCallsInHalfOpenState: 2
        ignoreExceptions:
          - personal.appointment_ms.exceptions.DoctorNotFoundException
          - feign.FeignException.BadRequest      # 400
          - feign.FeignException.UnprocessableEntity  # 422

server:
  port: 8081


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}

  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://ms-registry-server:8761/eureka}


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics


scalar:
  enabled: false
  darkMode: true
  theme: deepSpace