spring:
  application:
    name: appointment-ms

  profiles:
    default: prod

  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST:http://localhost:7777}"

  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKER:kafka-hospital:29092}

      bindings:
        appointment-created-out-0:
          destination: appointment-created
          content-type: application/json

        appointment-confirmed-out-0:
          destination: appointment-confirmed
          content-type: application/json
        appointment-completed-out-0:
          destination: appointment-completed
          content-type: application/json

        appointment-canceled-out-0:
          destination: appointment-canceled
          content-type: application/json
    openfeign:
      circuitbreaker:
        enabled: true


  datasource:
    username: ${db.username:postgres}
    password: ${db.password:123456}
    url: ${db.url:jdbc:postgresql://localhost:5434/hospital_db}
    hikari:
      connection-timeout: ${db.connection-timeout:30000}
      maximum-pool-size: ${db.maximum-pool-size:10}

resilience4j:
  circuitbreaker:

    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

    instances:

      patient-ms:
        baseConfig: default
        ignoreExceptions:
          - personal.appointment_ms.exceptions.PatientNotFoundException
          - feign.FeignException.BadRequest
          - feign.FeignException.UnprocessableEntity

      doctor-ms:
        baseConfig: default
        ignoreExceptions:
          - personal.appointment_ms.exceptions.DoctorNotFoundException
          - feign.FeignException.BadRequest
          - feign.FeignException.UnprocessableEntity
server:
  port: 8081


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}

  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://ms-registry-server:8761/eureka}


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics


scalar:
  enabled: false
  darkMode: true
  theme: deepSpace