spring:
  application:
    name: billing-ms

  profiles:
    default: prod

  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST:http://localhost:7777}"

  cloud:
    function:
      definition: appointmentCompletedConsumer
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKER:kafka-hospital:29092}

      bindings:
        appointmentCompletedConsumer-in-0:
          destination: appointment-completed
          group: billing-ms
          content-type: application/json
          

  datasource:
    username: ${db.username:postgres}
    password: ${db.password:123456}
    url: ${db.url:jdbc:postgresql://localhost:5434/hospital_db}
    hikari:
      connection-timeout: ${db.connection-timeout:30000}
      maximum-pool-size: ${db.maximum-pool-size:10}

server:
  port: 8081

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}

  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://ms-registry-server:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

scalar:
  enabled: true
  darkMode: true
  theme: deepSpace