spring:
  application:
    name: billing-ms

  profiles:
    default: prod

  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST:http://localhost:7777}"

  cloud:
    function:
      definition: appointmentCompletedConsumer

    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKER:kafka-hospital:29092}
          configuration:
            "[enable.auto.commit]": false

      bindings:
        appointmentCreatedConsumer-in-0:
          destination: appointment-created
          group: billing-ms
          content-type: application/json
          consumer:
            max-attempts: 3
        
        appointmentUpdatedStatusConsumer-in-0:
          destination: appointment-updated-status
          group: billing-ms
          content-type: application/json
          consumer:
            max-attempts: 3

        appointmentCreatedTypeConsumer-in-0:
          destination: appointment-created-type
          group: billing-ms
          content-type: application/json
          consumer:
            max-attempts: 3
  datasource:
    username: ${db.username:postgres}
    password: ${db.password:123456}
    url: ${db.url:jdbc:postgresql://localhost:5434/hospital_db}
    hikari:
      connection-timeout: ${db.connection-timeout:30000}
      maximum-pool-size: ${db.maximum-pool-size:10}

server:
  port: 8081
  servlet:
    context-path: /billings

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}

  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://ms-registry-server:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

scalar:
  enabled: false
  darkMode: true
  theme: deepSpace