spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false   # NO se registra a sí mismo
    fetch-registry: false         # NO descarga lista de otros servicios