package personal.appointment_ms.exceptions;

public enum ErrorCode {

    APPOINTMENT_TYPE_NOT_FOUND,
    APPOINTMENT_TYPE_ALREADY_INACTIVE,
    APPOINTMENT_NOT_FOUND,
    PATIENT_NOT_FOUND,
    DOCTOR_NOT_FOUND,
    PATIENT_SERVICE_UNAVAILABLE,
    DOCTOR_SERVICE_UNAVAILABLE
}   