server:
  port: 8081

  servlet:
    context-path: /medical-records

spring:

  application:
    name: medical-record-listener

  cloud:

    function:
      definition: medicalRecordProcessor

    stream:

      kafka:
        binder:
          brokers: ${KAFKA_BROKER:kafka-hospital:29092}

      bindings:
        appointmentStateProcessor-in-0:
          destination: appointment-created
          group: medical-record-appointment-created
          content-type: application/json

        appointmentStateProcessor-in-1:
          destination: appointment-updated-status
          group: medical-record-appointment-updated
          content-type: application/json

        appointmentStateProcessor-out-0:
          destination: appointment-state
          content-type: application/json

        medicalRecordProcessor-in-0:
          destination: appointment-state
          group: medical-record-processor
          content-type: application/json

        medicalRecordProcessor-in-1:
          destination: payment-update-status
          group: medical-record-payment
          content-type: application/json

        medicalRecordProcessor-out-0:
          destination: medical-record-ready
          content-type: application/json

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}

  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://ms-registry-server:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

scalar:
  enabled: false
  darkMode: true
  theme: deepSpace